name: swifty_companion
description: "A companion app for 42 students"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  catppuccin_flutter: ^1.0.0
  flutter_dotenv: ^5.2.1
  oauth2_client: ^3.3.0
  http: ^1.2.2
  logger: ^1.2.2
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.2
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  retrofit: ^4.4.1
  flutter_svg: ^2.0.14
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  retrofit_generator: ^8.2.1

flutter:
  uses-material-design: true
  assets:
    - .env